language: node_js # 构建所需的语言环境
node_js:
  - "v10.16.0"  # 对应的版本
branches:
  only:
  - master    # 构建的分支
cache:
  directories:
  - node_modules # 依赖缓存的目录
before_install:
- export TZ='Asia/Shanghai'  # 设置时区

before_install:
- openssl aes-256-cbc -K $encrypted_3298a3250f93_key -iv $encrypted_3298a3250f93_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
# 改变文件权限
- chmod 600 ~/.ssh/id_rsa 
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
# 配置 git 替换为自己的信息
- git config --global user.name 'DevinShi2019'
- git config --global user.email a2529151969@163.com
- git config --list

# 安装依赖

install:
- npm install hexo-cli -g
- hexo -v
- npm install

# 部署的命令
script:
- npm run deploy  # hexo clean && hexo g -d